### ISSUE TITLE
There is no proper folder structure you are maintaining

### ISSUE THREAD

**Issue by the-vis-sharma** [usha-gupta/Company-Website#10]
Please maintain a proper folder structure so all files are messuped what will happen when you will have 100 of files so how will you manage all?. Search on the net and find the best one but it should be like this -
Company Website
    |-- images
    |-- docs
    |-- html
    |-- home.html

The only home page should be outside other files should be in their respective folders.

**Comment by usha-gupta** [comment]
Yes, I should maintain a proper structure not I updated it you check
