### ISSUE TITLE
When you want both paragraph to be in center then why are you using two center tags for both?

### ISSUE THREAD

**Issue by the-vis-sharma** [usha-gupta/Company-Website#14]
https://github.com/usha-gupta/Company-Website/blob/bca6555114fd00a929aa67aea40a233dceb3152d/gallary.html#L32-L33

You can use single center tag and in that, you can put both paragraph tags. will it not work the same as you want?

**Comment by usha-gupta** [comment]
Yes, This is my mistake now I solve this problem
