### ISSUE TITLE
Why the height is in %tage for table? And Do you actually need height here?

### ISSUE THREAD

**Issue by the-vis-sharma** [usha-gupta/Company-Website#2]
https://github.com/usha-gupta/Company-Website/blob/191e3d0c70287557d210e905ed4c46e014acc486/home.html#L9

**Comment by usha-gupta** [comment]
According to me when I'm using color by table-wise at that time if I did not use then it will show background white color so overcome this problem I was using height in a table. but now I'm using color from the body so no need to used height tag here 
fixed issues
