### ISSUE TITLE
18*4 + 40 = ???

### ISSUE THREAD

**Issue by the-vis-sharma** [usha-gupta/Company-Website#3]
Can you tell me for this row in the table what will be the total width? As you have specified 18% for 4 columns and 40 for the next one so what will be total 18*4+40 = ?? Can %tage be more than 100? is it really possible? Divide the width accordingly, please. And until you don't need height and width don't specify manually. Always write minimum code and see the output if you need some changes then only add extra attributes. Otherwise not.

https://github.com/usha-gupta/Company-Website/blob/191e3d0c70287557d210e905ed4c46e014acc486/home.html#L11-L15

**Comment by usha-gupta** [comment]
answer is = 112
This is a calculation mistake now I solved it. 
fixed issues
